docker tag nanoserverapiscan stefanscherer/nanoserverapiscan:latest
docker tag nanoserverapiscan:onbuild stefanscherer/nanoserverapiscan:onbuild
docker push stefanscherer/nanoserverapiscan:latest
docker push stefanscherer/nanoserverapiscan:onbuild
