FROM microsoft/windowsservercore:10.0.14393.2007

ENV MONGO_VERSION 3.2.11

RUN powershell -Command wget -Uri https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-${env:MONGO_VERSION}-signed.msi -OutFile mongodb.msi -UseBasicParsing

RUN msiexec.exe /q /i mongodb.msi INSTALLLOCATION=C:\mongodb ADDLOCAL=Server,Client,MonitoringTools,ImportExportTools,MiscellaneousTools
