FROM microsoft/nanoserver:1709 AS prep
WORKDIR /busybox
ADD https://github.com/jhowardmsft/busybox64/raw/master/busybox.exe busybox.exe
USER ContainerAdministrator
RUN FOR /f "tokens=*" %i IN ('busybox --list') DO mklink C:\busybox\%i.exe busybox.exe
USER ContainerUser
FROM stefanscherer/curl-windows:1709
COPY --from=prep /busybox/ /busybox
USER ContainerAdministrator
RUN setx /M PATH "C:\busybox;%PATH%"
USER ContainerUser
ENTRYPOINT ["cmd.exe", "/s", "/c"]
